logging:
  level:
    com:
      example: TRACE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=stem
    username: stem
    password: password
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
